---
title: "lab5"
format: gfm
editor: visual
---

```{r}
# Load required packages
library(tidyverse)
library(knitr)

# Read in the data
titanic <- read_csv("https://raw.githubusercontent.com/nt246/NTRES-6100-data-science/master/datasets/Titanic.csv")

# Let's look at the top 5 lines of the dataset
head(titanic, n = 5) %>%
  kable()
```

```{r}
notes <- read_csv("https://raw.githubusercontent.com/nt246/NTRES-6100-data-science/master/datasets/Notes.csv")
kable(notes)
```

```{r}
length(titanic$PassengerId)
q1 <- titanic |> 
  summarise(survival_count = sum(Survived), dead_count = length(PassengerId)-sum(Survived)) |> 
  mutate(survival_rate = survival_count/(survival_count+dead_count))

kable(head(q1))
```

```{r}
q2 <- titanic |> 
  count(Sex)

q2

q2.1 <- titanic |> 
  group_by(Pclass) |> 
  count(Sex)

q2.1

ggplot(data = q2.1, mapping = aes(x = Sex, y = n)) +
  geom_col() +
  facet_wrap(~Pclass)
```

```{r}
q3 <- titanic |>
  mutate(survived = ifelse(Survived==0, "no", "yes")) |>
  group_by(Sex, survived) |>
  count() |>
  group_by(Sex) |>
  mutate(percentage = round(n/sum(n)*100, 2))
kable(q3)
```

```{r}
q4 <- titanic |>
  mutate(age_info = ifelse(is.na(Age), "missing", "available")) |>
  count(age_info)
kable(q4)
```

```{r}
titanic |>
  filter(!is.na(Age)) |>
  ggplot(aes(x=Age, fill=Sex)) +
  geom_histogram() +
  facet_grid(Pclass~Sex)
```

```{r}
titanic |>
  filter(!is.na(Age)) |>
  mutate(survived = ifelse(Survived==0, "no", "yes")) |>
  ggplot(aes(x=Age, fill=survived)) +
  geom_histogram(position="stack", color="black") +
  facet_grid(Sex~Pclass)
```

```{r}
titanic |>
  mutate(n_family=SibSp+Parch) |>
  ggplot(aes(x=n_family)) +
  geom_bar() +
  scale_x_continuous(breaks = 0:10)

titanic |>
  mutate(n_family=SibSp+Parch, with_family=ifelse(n_family>0, "yes", "no")) |>
  ggplot(aes(x=with_family)) +
  geom_bar() +
  coord_flip()
```

```{r}
titanic |>
  mutate(n_family=SibSp+Parch) |>
  ggplot(aes(x=n_family)) +
  geom_bar() +
  scale_x_continuous(breaks = 0:10) +
  facet_wrap(~Pclass, ncol = 1)

titanic |>
  mutate(n_family = SibSp+Parch, ticket_class = as.character(Pclass)) |>
  ggplot(aes(x = n_family, fill = ticket_class)) +
  geom_bar(color = "black", position = "fill") +
  scale_x_continuous(breaks = 0:10) +
  ylab("proportion") +
  coord_flip()
```

```{r}
titanic |>
  group_by(Ticket) |>
  mutate(n_ticket=n(), fare_per_ticket = Fare/n_ticket) |>
  ungroup() |>
  summarise(average_fare = mean(fare_per_ticket))
```

```{r}
titanic |>
  group_by(Ticket) |>
  mutate(n_ticket=n(), fare_per_ticket = Fare/n_ticket, ticket_class=as.character(Pclass)) |>
  ggplot(aes(x=fare_per_ticket)) +
  geom_histogram(bins = 100) +
  facet_wrap(~ticket_class, ncol = 1, scales = "free_y")
```
