---
format: gfm
editor: visual
---

```{r}
# Load required packages
library(tidyverse)
library(knitr)

# Read in the data
whales <- read_csv("https://raw.githubusercontent.com/nt246/NTRES-6100-data-science/main/datasets/whales.csv")
whales |> head() |> kable()
```

```{r}
whales_long <- whales |>
  pivot_longer(-1, names_to = "species", values_to = "info")
whales_long |> head() |> kable()
```

```{r}
whales_clean <- whales_long |>
  filter(!is.na(info))
whales_clean |> head() |> kable()
```

```{r}
whales_split <- whales_clean |>
  separate(info, c("date", "outcome", "size", "ocean"), ",")
whales_split |> head() |> kable()
```

```{r}
whales_parsed <- whales_split |>
  type_convert(
    col_types = cols(
      date = col_date(format = "%m/%d/%y"),
      size = col_integer()
    )
  )
whales_parsed |> head()
```

```{r}
whales_parsed |> 
  group_by(species) |> 
  summarise(number_of_ship_strikes = n(), average_size = mean(size, na.rm = T))  |>
  kable()
```

```{r}
whales_parsed |>
  mutate(ocean = ifelse(ocean == "artic", "arctic", ocean)) |>
  ggplot(aes(x=date, y = size, color=outcome)) +
  geom_point() +
  facet_grid(ocean~species)
```

```{r}
# Load required packages
library(babynames) # install.packages("babynames")

babynames |> head() |> kable()
```

```{r}
top_6_boy_names <- babynames |>
  filter(sex == "M") |>
  group_by(name) |>
  summarise(total_count=sum(n)) |>
  slice_max(order_by = total_count, n = 6)

top_6_girl_names <- babynames |>
  filter(sex == "F") |>
  group_by(name) |>
  summarise(total_count=sum(n)) |>
  slice_max(order_by = total_count, n = 6) 

babynames |>
  filter(
    (name %in% top_6_boy_names$name & sex == "M") | (name %in% top_6_girl_names$name & sex == "F")
    ) |>
  ggplot(aes(x=year, y=prop, group=name, color=sex)) +
  geom_line() +
  facet_wrap(~name)
```

```{r}
babynames |>
  mutate(decade = floor(year/10)*10) |>
  group_by(sex, decade, name) |>
  summarise(total_count = sum(n)) |>
  group_by(sex, decade) |>
  slice_max(order_by = total_count, n=1) |>
  ggplot(aes(x=decade, y=total_count, color=sex)) +
  geom_line(size = 1.5) +
  geom_point(size = 3)+
  ggrepel::geom_label_repel(aes(label=name)) +
  cowplot::theme_cowplot()
```
